[package]
name = "tax-zk"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
alloy-sol-types = { workspace = true }
