[package]
name = "financoor-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
alloy-sol-types = { workspace = true }
thiserror = { workspace = true }
